messages:
  money_received_enabled: true  # Habilita/desabilita a mensagem no chat
  money_received: "§aVocê quebrou um bloco de §e%block%§a e recebeu §6$%amount%§a"  # Mensagem padrão do chat

  money_received_actionbar_enabled: true  # Habilita/desabilita a mensagem na ActionBar
  money_received_actionbar: "§aVocê quebrou §e%block%§a e ganhou §6$%amount%§a!"  # Mensagem padrão da ActionBar

  # Mensagem da Picareta
  pickaxelore: "&aVocê recebeu a &6&lPicareta Lendária!"


  # Mensagem do reload plugin
  reload_message: "§aO plugin foi recarregado com sucesso!"
  # Mensagens Upgrade Menuy
  pickaxeupgleveleffi: "§aVocê aplicou o upgrade de Eficiência! Custo: §e{price}§a"
  pickaxemaxleveleffi: "§cEste item já está no nível máximo de Eficiência."
  pickaxeupglevelfort: "§aVocê aplicou o upgrade de Fortuna! Custo: §e{price}§a"
  pickaxemaxlevelfort: "§cEste item já está no nível máximo de Fortuna."
  moneyinsuficiente: "Você não tem dinheiro suficiente para este upgrade!"



upgrades:
  efficiencyUpgrade: 1000
  fortuneUpgrade: 5000
  speedUpgrade: 50

blocks price:
  DIAMOND_ORE:
    reward: 50.0
  IRON_ORE:
    reward: 10.0
  GOLD_ORE:
    reward: 15.0
  EMERALD_ORE:
    reward: 60.0
  COAL_ORE:
    reward: 5.0
  LAPIS_ORE:
    reward: 15.0
